version: "3.7"
services:
  postgres:
    image: postgres:12.4
    ports:
      - "5440"
    volumes:
      - ./docker-postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DATABASES="performance_psql_sr_t0", "performance_psql_sr_t1", "performance_psql_sw_t0", "performance_psql_sw_t1"
      - POSTGRES_USER=datahike
      - POSTGRES_PASSWORD=clojure
  mysql:
    image: mysql:8.0
    ports:
      - "3306"
    volumes:
      - ./docker-mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASES=performance_mysql_sr_t0, performance_mysql_sr_t1, performance_mysql_sw_t0, performance_mysql_sw_t1
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ONETIME_PASSWORD=clojure

  benchmarks:
    build: .
    ports:
      - "5000"
    depends_on:
      - postgres
      - mysql
    volumes:
      - db:/tmp/output-db
      - plots:/tmp/plots
      - errors:/tmp/errors
      - signals:/tmp/signals
    links:
      - postgres
      - mysql

  results:
    build: ./result-presentation
    ports:
      - "4000"
    depends_on:
      - benchmarks
    volumes:
      - db:/tmp/output-db
      - presentation:/tmp/presentation
      - signals:/tmp/signals

volumes:
  db:
    external:
      name: dh-benchmark-db
  plots:
    external:
      name: dh-benchmark-plots
  errors:
    external:
      name: dh-benchmark-errors
  presentation:
    external:
      name: dh-benchmark-presentation
  signals:
    external:
      name: dh-benchmark-signals
